workflows:
  flutter-build:
    name: Flutter US ID Photo Build
    environment:
      flutter: 3.41.6
      xcode: 15.4
    scripts:
      # 1. 强制指定 Flutter 版本，清除缓存
      - flutter --version
      - flutter channel stable
      - flutter upgrade
      - flutter clean
      - flutter pub cache repair
      - flutter pub get
      # 2. 用兼容参数构建，绕开v1检查
      - flutter build appbundle --release --no-tree-shake-icons --ignore-deprecation
      - flutter build ipa --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa