name: us_id_photo_maker
description: USA Passport Visa ID Photo Maker
version: 1.0.0+1

environment:
  sdk: '>=3.11.4 <3.12.0'
  flutter: '>=3.41.6 <3.42.0'

dependencies:
  flutter:
    sdk: flutter

  # 稳定图片选择
  image_picker: ^1.1.0
  # 正规图片处理，无坑
  image: ^4.2.0
  # 权限
  permission_handler: ^11.2.0
  # 相册保存
  gallery_saver: ^2.3.2
  # 路径工具
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true